### ISSUE TITLE
getdaglist script only returns first 100 dags

### ISSUE THREAD

**Issue by irdvl** [astronomer/cs-utility-nebula-to-astro#7]
Discovered this during migration, the script returns first 100 DAGs. We got around this by hardcoding a loop with `?offset=x` to paginate through results.

**Comment by iamakashladdha** [comment]
Hey @irdvl, Thanks for reaching out, it was a known Issue with the script as the Airflow API returns only the first 100 DAGs as it is the default limit. As a workaround you mentioned, we can use the offset parameter to go around this.

It was fixed here in this repo https://github.com/iamakashladdha/dagutil and is pending merge into migrate-to-astro Repo. We will get the fix merge ASAP.

Fix made was dynamic in nature and no hardcoding is needed for any number of Dags or offset parameters, It works as below.
- Total DAGs count is identified by API call to Airflow which acts as the max limiting parameter to get the dags
- Thereafter Loop is executed to get Dags in batches of 100 each by incrementing the Offset parameter by 100 till the total dag count is reached. 
- Output of all the Dags is appended to a single CSV file. Here's the sample output having 700+ Dags. https://github.com/iamakashladdha/dagutil/blob/main/output/output_dagdetails.csv

Hope this helps!

**Comment by iamakashladdha** [comment]
@irdvl: Merge for fix completed to get Dag List beyond 100 Dags. Thanks!
Closing the Issue.
